apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "sim-edge-app-device-scanner.fullname" . }}
  labels:
    app: {{ include "sim-edge-app-device-scanner.name" . }}
    chart: {{ include "sim-edge-app-device-scanner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.scale}}
  selector:
    matchLabels:
      app: {{ include "sim-edge-app-device-scanner.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "sim-edge-app-device-scanner.name" . }}
        release: {{ .Release.Name }}
    spec:
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
          - name: "verbose"
            value: '''True'''
          - name: "mqttHost"
            value: 'localhost'
          - name: "mqttPort"
            value: "1889"
          - name: "mqttAddr"
            value: {{ .Values.mqttAddr }}

            
          ports:
          - containerPort: {{ .Values.service.port }}
            name: "inv-hopr"
            {{- if not .Values.service.enabled }}
            hostPort: {{ .Values.hostPort }}
            {{- end }}
            protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.customResources.enablespecificdownload }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
     
